### ISSUE TITLE
Multicast und Windows funktionieren nicht zusammen

### ISSUE THREAD

**Issue by aloisr** [linuxmuster/linuxmuster-linbo#101]
Hallo,

ich habe gestern Multicast mit der Version lmn 7.0 getestet. Sollte der Windws 10 Client gesynct werden, dann funktionierte das mit Multicast nicht. Mit Torrent gehts. Der Linux Client funktionierte nach der Multicast-Übertragung  und dem syncen einwandfrei.

Bei Win 10 wurde das Cloop nicht vollständig übertragen bei 2,55GB von 6 GB ist Schluss. Die Datei  im Cache hat danach 0 Byte.

Gruß

Alois

**Comment by HappyBasher** [comment]
Hallo Alois, kann ich irgendwie nicht nachvollziehen. Dem Multicast ist es eigentlich wurscht, was in der cloop-Datei reingepackt ist. Bitte teste das nochmal bei Gelegenheit.
VG, Thomas

**Comment by HappyBasher** [comment]
Habe das mit 2.3.42-1 jetzt nochmal getestet. Läuft mit einem 18G großen Windows10-Image.

**Comment by aloisr** [comment]
Hallo Thomas,

ich lade gerade eine neue virtuelle Umgebung herunter. Wenn die läuft, dann teste ich noch einmal.

Gruß

Alois

**Comment by aloisr** [comment]
Hallo Thomas,

ich kam heute erst zum Testen. Mit der Version die ich jetzt habe funktioniert multicast.

Gruß

Alois
