### ISSUE TITLE
adjust Partitionsize in /srv/linbo/examples/start.conf.*

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo#103]
Hi Thomas,

i think the Partitionsizes in the old start.conf Examles Files are "outdated"
There are:
30GB for Windows and
10 GB for Ubuntu
I think the should be
40 GB for Windows
20 GB for ubuntu

Another thing is, that in those examplefiles (for non EFI Systems) every partition is Bootable.
We had only the cachepartition bootable and i had systems where it had to be that way.
It might not be importaint anymore: i just wanted to mention it.

LG 
Holger

**Comment by HappyBasher** [comment]
Which partition sizes do you suggest?
In my experience on some bios systems all os partitions including linbo partition should be bootable to work. It is harmless on systems where it is not necessary.

**Comment by baumhof** [comment]
Hi HappyBasher,

I think it should be at least
40 GB for Windows
20 GB for ubuntu

In my running Environments i use 50G for Windows and 26G for Ubuntu.
So we ether take the lower End (see above) or we plan ahead:
50 GB for Windows
30 GB for ubuntu

SSDs in the Client will be at 120GB since at least 2 Years: so planing 80G for the Operatingsystems leaves ~ 40G for Images: should be enough.

Concerning the bootable Flag: its been a while since i last experianced problems with this: so we can leave ist like that trusting your Experiance :-)

LG
Holger

**Comment by HappyBasher** [comment]
Done, see commit fc5c165.
