### ISSUE TITLE
Name of Sambadomain in Setup

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo#104]
In linuxmuster-setup only one Domain Name is asked for.
It used to be two: a Samba Domain and a Unix Domain.
And now: -d <domainname>, --domainname=<domainname> : Set domainname.
So i give a domain Name like: linuxmuster.lan
And this will be used as Samba Domain as well.
Fine with me, if its not possible to give a extra Domainname like SCHULE for AD, but it should be accompanied with a Tip, that this Domain will be used as Samba Domain as well.

ANother thought on that: is it possible for the setupscript to replace the Domainname SCHULE in the image.reg Patches located in /srv/linbo/ ?

Yours 
Holger

**Comment by HappyBasher** [comment]
In 2.3.40 for lmn7 reg files will be patched with sambadomain.
