### ISSUE TITLE
status in linbo-remote -l

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-linbo#105]
https://github.com/linuxmuster/linuxmuster-linbo/blob/4641fdd11cc8271d4d364c6c58af7f70dacb6307/files/lmn6/usr/share/linuxmuster-linbo/linbo-remote.sh#L101

`status` is `$4`, `$2` is date.

**Comment by HappyBasher** [comment]
Fixed in 2.3.43.
