### ISSUE TITLE
Windows will jetzt ein chkdsk

### ISSUE THREAD

**Issue by helge42** [linuxmuster/linuxmuster-linbo#106]
Ich habe die Version 2.3.40 installiert und sonst nichts geändert. 
Nach dem Neuaufsetzen von Windows (roter Knopf in linbo) wird beim Starten von Windows ein chkdsk durchgeführt. Das war bei Version 2.3.38 nicht der Fall.

Die Konfiguration ist in  #102 beschrieben. #102 sollte auch wieder geöffnet werden.

Viele Grüße, Helge

**Comment by PLanB2008** [comment]
Did you try to run chckdsk, write another image from this installation and try to sync this?

We need to know if the image get corrupted by linbo

**Comment by HappyBasher** [comment]
I'm sorry I'm not able to reproduce this issue. On my systems partition labels persist, and there is no chkdsk after sync. Seems to me to be a support case.

**Comment by helge42** [comment]
I have made a new windows-image. The chkdsk-message is gone. This may get closed.

But the problem with the label for the first partition pesists. I have followed [this](https://github.com/linuxmuster/linuxmuster-linbo/issues/102#issuecomment-461587543) steps. The label is not there.

What can I test for this?

**Comment by helge42** [comment]
After some reading I will do tomorrow some testing with linbo-remote and linbo-ssh. 
...

**Comment by helge42** [comment]
### Reproduce the label-error

in linbo-gui select partition.
Then:
```
linbo-ssh
# blkid 
/dev/sda1: LABEL="windows" UUID="3F46E61F7DE5D42B" TYPE="ntfs" PTTYPE="dos" PARTUUID="b5c413b3-01"
```
label is there
`# linbo-remote -i 10.16.199.12 -c format:1`
label is there

`linbo-remote -i 10.16.199.12 -c format:1,sync:1
~ # blkid
/dev/sda1: UUID="0D7D0B5277083BAC" TYPE="ntfs" PARTUUID="4fbf0664-01"`
label is gone!
Probably the sync command is the problem (or ntfsclone inside from sync ???)

The command `linbo-remote -i host -c partition` do not bring the labels back. Only `linb-remote -i host -c label`. So the linbo-gui command partition works different, because this sets the labels. 

Perhaps the "Red Button" uses the equivalent to `linbo-remote -i host -c sync:1` , which erases the label.

**Comment by helge42** [comment]
The label of a windows partitions is saved in the image file. This will come in action regardless of whether is writen by the partition or format programm. I think this is done by ntfsclone.

The label for a windows partition must be present when building an image to take effect.
