### ISSUE TITLE
Linbo: Kein Sync oder neu bei Windows ohne Netzwerkkabel

### ISSUE THREAD

**Issue by Markus1301** [linuxmuster/linuxmuster-linbo#108]
Setup: Linunxmuster.net 6.2 
Linbo: 2.3.40-0
Client: Win 7 Pro, Boot Methode BIOS

Wenn kein Netzwerkkabel gesteckt ist, laufen die Tasten SYNC und NEU ohne Fehlermeldung durch, bis der Neustart kommen würde. Der Rechner bleibt zu diesem Zeitpunkt unter Linbo stehen. Über die START Taste lässt sich Windows dann normal starten.

Mit Netzwerkkabel verhält sich der Rechner völlig normal.

Diskussion zu diesem Problem: https://ask.linuxmuster.net/t/synchronisation-von-offline-clients-notebooks/2142

Dort wurde gesagt, dass dieses Problem bei Linux auf dem Client nicht auftritt.

**Comment by jr-lml** [comment]
Hallo,

das ist ein kleiner Bug in linbo_cmd, Deteils und Lösung siehe meinen letzten Post im Forum.

Beste Grüße Jörg
