### ISSUE TITLE
linbo_cmd: mk_linefiboot has wrong return value

### ISSUE THREAD

**Issue by fschuett** [linuxmuster/linuxmuster-linbo#109]
Hallo,
in line 1212: [ "$RC" = "0" ] || touch "$doneflag"
should be: [ "$RC" = "0" ] && touch "$doneflag"

RC=0 means success, so $doneflag should be touched, if RC=0.

**Comment by fschuett** [comment]
actually mk_linefiboot !

**Comment by HappyBasher** [comment]
Fixed in 2.3.49. Thanks for your contribution.
