### ISSUE TITLE
WoL is missing in V7 Linbo

### ISSUE THREAD

**Issue by netzint** [linuxmuster/linuxmuster-linbo#112]
linbo-remote -r r100 -w 20 -c partition,format,initcache:torrent,sync:1,start:1
….
Trying to wake up:
 10.0.100.1 ... /usr/sbin/linbo-remote: Zeile 371: get_mac: Befehl nicht gefunden
 is not a hardware address and I could not resolve it as to an IP address.

**Comment by HappyBasher** [comment]
Fixed in linuxmuster-linbo [2.3.50](https://github.com/linuxmuster/linuxmuster-linbo/tree/2.3.50).
