### ISSUE TITLE
Optimierung für die Aktivierung von Windows durch linbo

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo#114]
Hallo,
mich hat ein Vorschlag zu einer Optimierung in linbo erreicht: 
----------------
Dabei ist mir aufgefallen, dass beim Suchen der Tokens vom find Prozess einige Fehler ausgegeben werden. Dies führt dazu, dass alle Fehler von find ins tar archive verpackt werden.
Diese Fehlermeldungen repräsentieren aber kein physisches File in der Partition.

Mein Vorschlag wäre:
anstatt $(find "$windir" -iname tokens.dat) // in Zeile 376 linbofs/init.sh

$(find "$windir" -iname tokens.dat 2>&1 | grep -v error) ausführen. (filtern aller error Ausgaben)
-----------------

Viele Grüße

Holger

**Comment by HappyBasher** [comment]
Ist das immer noch aktuell? Ich habe hier keine error-Dateien in den tar files.

**Comment by baumhof** [comment]
... ich finde leider gerade nciht, wer mir das gemeldet hat ..
In welchem tar file sollen den da Fehler sein?
Dann schau ich mal in meine rein.

**Comment by HappyBasher** [comment]
Assuming that is no longer current.
