### ISSUE TITLE
Backup and restore of supplementalCredentials

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo#115]
In addition to _unicodePwd_ linbo should also backup the ad computer account field  _supplementalCredentials_ to the image macct file and restore it on system start to better protect domain membership. This is especially important if you have multiple operating systems installed on the same machine.

**Comment by HappyBasher** [comment]
Fixed in [2.3.52](https://github.com/linuxmuster/linuxmuster-linbo/compare/2.3.51...2.3.52).

**Comment by HappyBasher** [comment]
This is not necessary for worksation $-accounts and should be removed in the next release.

**Comment by PLanB2008** [comment]
Maybe we should discuss why it was added in the first place. I assume there was a reason for it @jeffbeck  ?

**Comment by HappyBasher** [comment]
we'll leave it as usual
