### ISSUE TITLE
.postsync nach Sync nicht mehr da

### ISSUE THREAD

**Issue by white-rabbit07** [linuxmuster/linuxmuster-linbo#116]
LInbo unter v7 macht zZ folgendes:
Ich habe ein cloop auf dem Server. Das Gesamtpaket besteht aus 6 Files, und zwar
.cloop .desc .info .macct .postsync und .torrent

Wenn ich ein neues Image anlege und hochlade, wird bekanntlich das alte Image umbenannt. Dabei wird aber die Postsync-Datei auch umbenannt und für das aktuelle Image steht die Datei dann nicht automatisch zur Verfügung! Das habe ich bereits wiederholt beobachtet, so dass ich von einem Bug ausgehe.

**Comment by white-rabbit07** [comment]
Das Problem tritt nur dann auf, wenn die Rechte der Datei nicht stimmen. Die Postsync-Datei MUSS 
offenbar 664 als Zugriffsrecht besitzen; ansonsten wird die Datei auch nicht auf den Client übertragen

**Comment by HappyBasher** [comment]
Published in linuxmuster-linbo7 2.3.64.
