### ISSUE TITLE
linbo setzt beim lokalen update von linbo per PXE den reboot nicht richtig

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo#121]
Hier ist ein Problem aufgekommen:

https://ask.linuxmuster.net/t/grub-soll-bei-pxe-boot-automatisch-linbo-starten/4515/7

LG

Holger

**Comment by HappyBasher** [comment]
Ehrlich gesagt, werd ich nicht ganz schlau daraus. Was ist denn genau der Fehler bzw. das erwartete Verhalten?

**Comment by HappyBasher** [comment]
Unklar, was hier genau gefixt werden soll.
