### ISSUE TITLE
create_efiboot() fails with NVMe devices

### ISSUE THREAD

**Issue by itkpeter** [linuxmuster/linuxmuster-linbo#123]
`linbofs: /usr/bin/linbo_cmd` line 1022 function `create_efiboot()`:
`local efipartnr="$(echo "$efipart" | sed "s|$efidisk||")"`

on SATA systems `$efipart` containing "/dev/sda1" and `$efidisk` containing "/dev/sda" will result in `$efipartnr` containing "1".

on NVMe systems `$efipart` containing "/dev/nvme0n1p1" and `$efidisk` containing "/dev/nvme0n1" will result in `$efipartnr` containing "p1".
This will cause the efibootmgr command at line 1034 to fail, complaining about wrong data in part number.

Thus, with a fresh installed EFI NVMe system the function `repair_efi()` returns an error, won't restore the EFI boot files and falls back starting the OS by grub reboot. In addition, there will be no boot entries in EFI partition and the OS will only be bootable when starting Linbo via PXE.

quick and dirty changing line 1022 to
`local efipartnr="$(echo "$efipart" | sed "s|$efidisk||" | sed "s|p||")"`
fixes the issue.

**Comment by itkpeter** [comment]
This issue affects all EFI systems with NVM storage, which will be most of the current and upcoming workstation hardware.
A soon linbo update with a fix would really be appreciated.

**Comment by HappyBasher** [comment]
Fix published in [linuxmuster-linbo 2.3.62](https://github.com/linuxmuster/linuxmuster-linbo/compare/2.3.61...2.3.62). Thank you for your contribution.
