### ISSUE TITLE
Errors with wakeonlan (linbo-remote -w) in linuxmuster-linbo 2.3.58

### ISSUE THREAD

**Issue by foer** [linuxmuster/linuxmuster-linbo#127]
With the new linuxmuster-linbo there is an issue with wakeonlan.

`linbo-remote -i <IPADRESSE o. HOSTNAME> -w0`

gives the following error message and the client doesn't wake up.

```
Trying to wake up:
 IPADRESSE ... IPADRESSE is not a hardware address and I could not open /etc/ethers.
```

**Comment by PLanB2008** [comment]
What are you trying to accomplish there? 

Running linbo 2.3.59-0

this works flawlessly for me. 

Does 
    wakeonlan MACADDRESS

work for you?

**Comment by foer** [comment]
This issue was  resolved by Thomas two weeks ago.
