### ISSUE TITLE
missing timezone

### ISSUE THREAD

**Issue by ni-kw** [linuxmuster/linuxmuster-linbo#128]
In linbo 2.3.59 there is no `/etc/localtime` file. So the time in linbo is UTC. It is the correct time of the server, but UTC. (Client 13:00, Server 15:00)

After a few times of `update-linbofs` still no file.
If do `linbo-scp /usr/share/zoneinfo/Europe/Berlin r101-pc11:/etc/localtime` the time in linbo changes to the correct localtime immediately.

https://ask.linuxmuster.net/t/linbo-zeitsync/4818/12

Before I have updated to 2.3.59 there was 2.3.57 installed. In 2.3.57 there was a `/etc/localtime` but with a different md5sum to the server
```
root@server:~# md5sum /usr/share/zoneinfo/Europe/Berlin
2d53644b5272b0826ad62a3317a66bb9  /usr/share/zoneinfo/Europe/Berlin
```
```
~ # md5sum /etc/localtime
fe9ad2d5c4c79122a99b4d5ed44fda0e  /etc/localtime
```

**Comment by PLanB2008** [comment]
The mistake is in update-linbofs around 

 94  [ -n "$zi" -a -e "$zi" ] && cp -L "$zi" etc/localtime

I'm not sure what the -a -e is about, wouldn't it be sufficend just to copy /etc/localtime in etc/localtime if /etc/localtime exists?
