### ISSUE TITLE
create_cloop und upload_cloop won't work anymore

### ISSUE THREAD

**Issue by jolly-jump** [linuxmuster/linuxmuster-linbo#129]
Hi.
```
linbo-remote -i r202-pc01 -p create_cloop:1
```
schmeißt einfach den Bettel hin. 
Wenn sich was an der Syntax geändert hat, hab ich es verpasst.
Gleiches gilt für upload_cloop:1

partition,label,initcache:torrent/rsync,start,reboot,sync:1 
funktionieren alle.

```
ii  linuxmuster-linbo-common7             2.3.59-0                                        all          linuxmuster-linbo common files: kernel, initrd and pxe boot configuration
ii  linuxmuster-linbo7                    2.3.59-0                                        all          linuxmuster-linbo scripts
```

**Comment by foer** [comment]
Temporärer Workaround:
`linbo-remote`
mit einem funktionierenden Flag, z.B. start:1 absenden, dabei wird unter 
`/srv/linbo/linbocmd`
eine Datei (ein onboottask) mit
`hostname.cmd`
angelegt. In diese die nicht funktionierenden Flags eintragen und den client booten, dann werden die Sachen abgearbeitet.

**Comment by HappyBasher** [comment]
Fixed in linuxmuster-linbo7 2.3.61.
