### ISSUE TITLE
character encoding problem in linbo messages

### ISSUE THREAD

**Issue by goeba** [linuxmuster/linuxmuster-linbo#133]
I get wrong characters (like °A and other unicode-mismatch-garbage) in the linbo messages, for instance when partitioning.

I have had this error for a long time now, so it applies to the current and older versions, I think.

**Comment by HappyBasher** [comment]
Thank you for your comment, do you mean messages in the linbo client gui? Then, I fear, this will never be fixed, because the further development of the old linbo client gui is not possible with reasonable effort.

**Comment by HappyBasher** [comment]
Will never fix.
