### ISSUE TITLE
It is not possible to use hyphens when adding computers via Linbo

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster/linuxmuster-linbo#134]

**Comment by garblixa** [comment]
Please modify documentation after fixing the bug:
https://docs.linuxmuster.net/de/latest/clients/linbo/linbo-imagingscreen.html?highlight=Linbo%20nutzen#dialog-registrieren

**Comment by MachtDochNix** [comment]
If you realize faster that it is fixed, and you have time and desire, I would be happy if you update it yourself. Lake: https://docs.linuxmuster.net/de/latest/appendix/contribute/docs/edit-on-github.html

**Comment by garblixa** [comment]
Thorsten, this should only be a hint to the developer, so that it is not forgotten that there is a hint to the bug in the documentation.
But thanks for the link how to change the documentation.

**Comment by HappyBasher** [comment]
I fear this will never be fixed, because the further development of the old linbo client gui is not possible with reasonable effort. The use of the webui is recommended to register new hosts.
