### ISSUE TITLE
Linbo fails when label exists

### ISSUE THREAD

**Issue by thoschi** [linuxmuster/linuxmuster-linbo#136]
When fdisk is trying to change the partition table, this fails if labels are already used on that disk.

A workaround is to change the labels, partition and change back the labels afterwards.

There should be a linbo-command to resolv such an issue. To call dd manually is no option if partitions for a big number of computers has to be changed.

I added a "wipe" command to my fork and created a pull request (#135 containing older stuff too, forgot to pull before) but anyway this has to be reviewed by someone knowing linbo better than I do).

**Comment by HappyBasher** [comment]
Thank you for your contribution. Added your dd based mbr wipe to mk_parted which is invoked every time partition() is called. This should be enough. There is no need for a supplemental wipe command in our opinion.
