### ISSUE TITLE
Unsupported Parse Point when syncing Win 10

### ISSUE THREAD

**Issue by thoschi** [linuxmuster/linuxmuster-linbo#138]
Linuxmuster 6.2 / Linbo 2.3.57.0

Since the Windows 10 Anniversary Update we get a (different) number of error messages when syncing Windows 10:
    [...] unsupported reparse point [...] input output error
The sync seems to take longer than format+sync and Windows is broken afterwards.
So for now Win10-Sync is broken for us.

It might be related to this: https://bugzilla.redhat.com/show_bug.cgi?id=1377049
Might a new version of the ntfs (including the mentioned plugin) solve this?

**Comment by PLanB2008** [comment]
This is not properly working since the introduction of sylinks in ntfs with windows vista. Nothing to do with windows 10

**Comment by HappyBasher** [comment]
So I suppose this will never fix? Workaround is to restore Windows 10 systems exclusively with the New & Start option?

**Comment by HappyBasher** [comment]
Closed because of more than 4 weeks of inactivity.
