### ISSUE TITLE
Termination if there is not enough space in the cache partition 

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster/linuxmuster-linbo#139]
With [Create and upload image] the error message that the new image does not fit into the cache is only briefly visible. It disappears in the displayed log and the uploaded image is defective.
1. the defective image must not be uploaded to the server, so no new lines would be written into the log.
2. the abort must be visible to the user in any case.

Message in the forum under: [https://ask.linuxmuster.net/t/keine-fehlermeldung-beim-erstellen-von-images-bei-zu-kleinem-cache/6132/14?u=machtdochnix](https://ask.linuxmuster.net/t/keine-fehlermeldung-beim-erstellen-von-images-bei-zu-kleinem-cache/6132/14?u=machtdochnix)

**Comment by HappyBasher** [comment]
I fear this will never be fixed within the gui because it ignores the return code of mk_cloop obviously. So this is fixed only within linbo-remote.
