### ISSUE TITLE
Feature Request: newer Kernel in linbo (5.4 lts)

### ISSUE THREAD

**Issue by foer** [linuxmuster/linuxmuster-linbo#140]
Almost all newer notebooks from lenovo, hp or asus, that i've tested over the last few weeks had problems with too old drivers in the linbo kernel. There are especially issues with uefi, grapics and lan-card support.
It would be nice, if you could integrate the new 5.4 lts kernel in linbo to support newer Hardware.

**Comment by HappyBasher** [comment]
Fixed, see [424f554](https://github.com/linuxmuster/linuxmuster-linbo/commit/424f554a01699dfb424405b2243a75c525beb5d7).
