### ISSUE TITLE
start.conf exmaple use /vmlinuz as starting point but this link is not created in all modern distributions

### ISSUE THREAD

**Issue by lemertens** [linuxmuster/linuxmuster-linbo#142]
Modern distributions (e.g. ubuntu 20.04,CentOS 7 )have stopped to create the symlink

    /vmlinuz -> /boot/vmlinuz-<atcutal version number> 

Same thing goes for initrd.img. So a Linbo Linux-Client configured with

     Kernel = vmlinuz
     Initrd=initrd.img
in start.conf will not boot unless the symlink is manually added. I propose to adapt linbo documentation and examples to use
Kernel=boot/vmlinuz
Initrd=boot/initrd.img
instead so Linux will boot regardless of wether /vmlinuz-Symlink exists or not

**Comment by jolly-jump** [comment]
one should add: 
the modern distribution started to create the symlink 
`/boot/vmlinuz -> /boot/vmlinuz-<version>`
and stopped using the old location.

What if the /boot partition is separate? 
I'm not sure if having /boot on a separate partition from "/" worked for linbo up to now.

and one more: this is a transition time. several distribution in the linux client will still use /vmlinuz etc.
I think linbo should not automatically search for /boot/vmlinuz or /vmlinuz although this would surely be easily possible.

**Comment by HappyBasher** [comment]
So, how should we treat this now? Can you provide sample files?

**Comment by lemertens** [comment]
> What if the /boot partition is separate?
> I'm not sure if having /boot on a separate partition from "/" worked for linbo up to now.
> 
i do not understand how this is related to my hint and proposition

> I think linbo should not automatically search for /boot/vmlinuz or /vmlinuz although this would surely be easily possible.

linbo does not search at all, it tries to start vmlinuz/initrd from the place where start.conf points it too. that is why i opened that issue, because my ubuntu stopped working when i upgraded to 20.04 which does no longer provide the symlinks /vmlinuz and /initrd.img  which was still config'ed in the start.conf i used.  

> and one more: this is a transition time. several distribution in the linux client will still use /vmlinuz etc.

i haven't looked up all distributions but as far as /boot is in general THE linux boot directory i would assume, that in general/boot/vmlinuz is the file and /vmlinuz is the symlink. 

An [Example file](https://github.com/linuxmuster/linuxmuster-linbo/files/5559696/example.zip)  is attached
