### ISSUE TITLE
/boot and /boot/efi fail to be unmounted, subsequent partitioning fails

### ISSUE THREAD

**Issue by fschuett** [linuxmuster/linuxmuster-linbo#145]
Hallo,
with some partitioning scheme Linbo mounts ntfs volume readonly as boot/efi and fails in command "mkdir boot/efi/EFI", which leaves the partition mounted, which prevents subsequent partitioning from working. I observed this behaviour with Lenovo netbooks, f.ex. Ideapad S130. The problem is solved, if Linbo checks the mkdir return code.
I attach a zip file with a patch for linbo_cmd.

**Comment by fschuett** [comment]
[umount_boot.patch.zip](https://github.com/linuxmuster/linuxmuster-linbo/files/5476249/umount_boot.patch.zip)

**Comment by HappyBasher** [comment]
Thank you for your contribution. Fix is published in 2.3.68.
