### ISSUE TITLE
linbo-remote: Handling of clients with dynamic ip (lmn7 only)

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo#148]
Dynamic ip clients don't have a fixed ip in devices.csv so linbo-remote is not able to handle them.

**Comment by fschuett** [comment]
What are dynamic ip clients? As soon as linbo registers a client, it assigns a fixed ip address, which is used. Are you talking about clients without lan adapters? For such clients I do use the wlan mac address for identification purposes. That works quite well. I can backport this.

**Comment by PLanB2008** [comment]
Dynamic ip clients are clients without a static DHCP lease.

**Comment by HappyBasher** [comment]
Instead of an ip address they have only a "DHPC" entry in devices.csv. So they work in different subnets with full linbo functionality.

**Comment by HappyBasher** [comment]
linbo-remote uses now the hostname instead of client's ip address. If ip is given as an argument the hostname will be queried with nslookup, so the dns should be properly configured.
