### ISSUE TITLE
Move new .svg icons into place?

### ISSUE THREAD

**Issue by CodeCrafter912** [linuxmuster/linuxmuster-linbo#162]
According to what @kiarn said [over here](https://github.com/linuxmuster/linuxmuster-webui7/issues/162), the new OS icons have to be placed [here](https://github.com/linuxmuster/linuxmuster-linbo/tree/master/files/common/var/linbo/icons).
Is that how you would like to do it, or should the linuxmuster-linbo-gui7 package handle this @HappyBasher ?
(note: all the new icons can be found [here](https://github.com/linuxmuster/linuxmuster-linbo-gui/tree/master/build/icons) )

Regards
Dorian

**Comment by HappyBasher** [comment]
As we discussed last friday the icons will be packed in the gui package. So nothing to here.

**Comment by CodeCrafter912** [comment]
Ok, moving this to the gui repo then
