### ISSUE TITLE
Linbo manipulates start.conf ?

### ISSUE THREAD

**Issue by CodeCrafter912** [linuxmuster/linuxmuster-linbo#163]
There seems to be some wired issue with Linbo that occurs when a partition layout is present on the drive that does not match the partitions described in the start.conf:
On the client drive I have the following partitions:
1. /dev/sda1 windows ntfs 
3. /dev/sda2 cache

In our start.conf on the server I have:
1. /dev/sda1 windows ntfs
2. /dev/sda2 ubuntu ext4
3. /dev/sda3 cache   ext4

But when Linbo is booted and I do `cat /start.conf` this is what I get:
1. /dev/sda1 windows ntfs
2. /dev/sda2 ubuntu ext4
3. /dev/sda2 cache   ext4

I could only reproduce this problem with the latest stable packages:
linuxmuster-linbo7 (2.3.68-0)
linuxmuster-linbo-common7 (2.3.68-0)

Any ideas what could cause this?

NOTE: I was able to reproduce this thanks to this comment: https://ask.linuxmuster.net/t/labelproblem-in-linbo/6681/5

**Comment by CodeCrafter912** [comment]
Looks like it happens here: https://github.com/linuxmuster/linuxmuster-linbo/blob/d5576d6f58d98804cb1b208725525ba802a723e6/linbofs/init.sh#L200

**Comment by HappyBasher** [comment]
This was introduced in 2.3.29 in conjunction with #78, but I don't know the details anymore, that was over three years ago. I'll throw this out, no problem.

**Comment by CodeCrafter912** [comment]
To be honest, I don't really understand what happened back then, but if you just remove it, will it reintroduce the problems?

**Comment by HappyBasher** [comment]
We will see. As far as I remember now it has to do with offline mode if the cached start.conf does not match the actual partitioning labelling.

**Comment by HappyBasher** [comment]
Works without issue on my multi os efi test client. Changed the partition scheme in start.conf and re-partitioned it with linbo. Not tested: offline mode, bios client.
