### ISSUE TITLE
linbo_cmd function to list all images in cache

### ISSUE THREAD

**Issue by CodeCrafter912** [linuxmuster/linuxmuster-linbo#165]
For the "upload image"  dialog in the linboGUI I need a function that does the following:

1. Mount the cache partition
2. Print all Images that are present in the cache partition (`ls /cache/*.cloop`)
3. Unmount the cache partition
4. Exit 0

I could do this manually, but I am trying to stick to using linbo_cmd as the only interface.
Would be nice to get this added :slightly_smiling_face:

**Comment by HappyBasher** [comment]
Ok, how is this done in the old gui?

**Comment by CodeCrafter912** [comment]
It isn't.
The old GUI just lists one image per OS with the name of the os base image.
It doesn't care if the images actually exist.

**Comment by HappyBasher** [comment]
Ah, Ok. Command could be `linbo_cmd listimages <cachedev>`. Output like `ls -1 *.cloop` or `ls -l *.cloop`? Or both controlled by parameter `long`?

**Comment by CodeCrafter912** [comment]
`ls -1 *.cloop` is enough. I think the other information that `-l` provides is irrelevant.

**Comment by CodeCrafter912** [comment]
I implemented this in the GUI using the -1 flag and `linbo_cmd listimages <cachedev>`

**Comment by HappyBasher** [comment]
Testings packages see
http://archive.lmndev.de/lmn7-testing/linuxmuster-linbo7_2.4.2-1_all.deb
http://archive.lmndev.de/lmn7-testing/linuxmuster-linbo-common7_2.4.2-1_all.deb
