### ISSUE TITLE
Auswerten ob sync auf ein NTFS, oder ein Linux Format ausgeführt werden soll

### ISSUE THREAD

**Issue by aloisr** [linuxmuster/linuxmuster-linbo#176]
Hallo Entwickler,

mir passiert es immer mal wieder, dass ich einer Windows Partition ein sync:1 und start:1 schicke. Das geht dann nicht gut aus. Deshalb meine Bitte/Anregung (wenn überhaupt und ohne viel Aufwand möglich) folgendes zur realisieren.

Bevor sync ausgeführt wird wird geprüft ob eine NTFS-Partition gesynct werden soll. Wenn ja, dann wird ein format:Partitionsnummer vorweggeschickt.

Vielen Dank für's drüber nachdenken

Alois

**Comment by PLanB2008** [comment]
Hallo Alois,

dabei handelt es sich klar um einen Bedienfehler. Sync:1 entspricht eben einem Synchronisiertem Start (auch "gelbstart" genannt).
Für den Rotstart ist auch unter Linux immer ein Format vorweg zu  senden. Wir arbeiten momentan generell an Linbo so dass in Zukunft auch wieder ein Windows Gelbstart möglich sein wird.
Das angefragte wäre konträr dazu ein Hack der auch wieder ausgebaut werden müsste sobald das wieder funktioniert.

**Comment by aloisr** [comment]
Hallo Andreas,

Vielen Dank für die Rückmeldung.

Lösch das Issue, oder erklärt es als gelöst.

Viele Grüße Alois

Andreas Till ***@***.***> schrieb am Fr., 12. März 2021,
09:46:

**Comment by PLanB2008** [comment]
Closed
