### ISSUE TITLE
FR: Make -n -d disable the GUI immidiately after boot

### ISSUE THREAD

**Issue by CodeCrafter912** [linuxmuster/linuxmuster-linbo#178]
Hi @HappyBasher,

There is an Issue with linbo-remote -c when used in conjunction with -w:
When a client has autostart enabled, it will just start instead of waiting for the ssh connection from the server. You previously solved this by setting all OSs to disabled.
I think this was removed in conjunction with #161. 
In my opinion the optimal solution would be to set the GuiDisabled = yes option in start.conf on boot via init.sh.

Would be nice to get that fixed as linbo-remote -c -w is mostly unusable currently.

**Comment by HappyBasher** [comment]
Not reproduceable here. `linbo-remote -w0 -p <command> -n -i <hostname>` works as expected. A configured autostart in start.conf will be suppressed.

**Comment by HappyBasher** [comment]
Does this make sense? In which scenario do you need a disabled gui after linbo has processed all remote commands on boot? I think in this case all is done and the gui is ready to wait for user interaction. Doesn't `linbo-remote -w <n> -c <cmd list> -d` meet all the requirements you need? Implementing this requirement means a certain effort, which must be very well justified.

**Comment by CodeCrafter912** [comment]
Let me explain again:
1. I execute linbo-remote -w 60 -n -d -c sync:1 -i test-client
2. Linbo starts and disables the autostart
3. Linbo is in a normally usable state
4. The 60 seconds delay has passed and the server starts executing commands
5. the GUI is disabled
6. commanda are executed
7. the GUI is re-enabled
8. Linbo is usable again

If someone happens to walk by the Client betweed step 3 and 4, they might shut it down because there is no indication that it will start syncing shortly and this is what I want to prevent. So in my opinion it would make sense to disable the GUI already at step 2. I do not need the Gui disabled after commands are executed but before. Wouldn't this just ne a case of expanding the onboot task of -n to disable the gui as well?

**Comment by CodeCrafter912** [comment]
(sorry, I mixed up -p and -c earlier, I am talking about -c)

**Comment by HappyBasher** [comment]
But if you do `linbo-remote -w 60 -n -p sync:1 -i test-client` you have achieved the same and no problem at all with users. So why implement something with effort which can be achieved otherwise?

**Comment by CodeCrafter912** [comment]
Okay, I see your point. Will you merge it if I implement it myself?

**Comment by CodeCrafter912** [comment]
I implemented if in #181 
Would be nice if you could take a look at it :)
There are actually not too many changes, the biggest one is that I had to move some code in gui_ctl into functions.

**Comment by HappyBasher** [comment]
Edited the title because -c -w do work in combination with autostart.

**Comment by CodeCrafter912** [comment]
Your have reverted my PR so please reopen this issue.

**Comment by CodeCrafter912** [comment]
I have re-opened the pr. It is not responsible for any of the mentioned issues, as far as I can tell.
https://github.com/linuxmuster/linuxmuster-linbo/pull/187
