### ISSUE TITLE
Bug: Upload of .log and .status files does not work with capital letters in Hostname

### ISSUE THREAD

**Issue by CodeCrafter912** [linuxmuster/linuxmuster-linbo#182]
Upload of .log and .status files does not work with capital letters in Hostname.

The problem is that this sed command:
https://github.com/linuxmuster/linuxmuster-linbo/blob/cd2f70d2df52f3b3ff284ea660d7914a679c9d59/files/lmn7/usr/share/linuxmuster/linbo/rsync-pre-download.sh#L71
does not work in that case, because `${compname}` does not reflect the capital letters.

**Comment by fschuett** [comment]
It could be fixed by appending the "I" flag to the busybox sed search command.

**Comment by CodeCrafter912** [comment]
Hi @fschuett 
Thanks fot the hint I'll try it tomorrow :)

By the way: I spent some time looking at your buildroot port of Linbo and we decided to port the upcoming linbo7 to buildroot as well. Would you be willing to help out here and there :) ?

Regards,
Dorian

**Comment by fschuett** [comment]
Hallo Dorian,
sure. I'm glad to hear this.
If you make it in a way that both branches, linbo7 and oss, overlap more, that would be
beneficial for all of us.

Frank

**Comment by CodeCrafter912** [comment]
Hi Frank,

I don't know a lot about oss, and we are planning to re-do the whole backend as well (probaply in Python). So we will have to see how this could be ecomplished :)

Regards,
Dorian

**Comment by CodeCrafter912** [comment]
Adding the I flag actually solved the issue, thanks @fschuett :)
@HappyBasher I did a PR on this.

**Comment by CodeCrafter912** [comment]
Your have reverted my PR so I am reopening this.
