### ISSUE TITLE
Sync fails with some cloops

### ISSUE THREAD

**Issue by helge42** [linuxmuster/linuxmuster-linbo#190]
Today we couldn't sync one of our cloop files with the newest linbo.

I have pointed out an error in linbo_cmd. My [pull request](https://github.com/linuxmuster/linuxmuster-linbo/pull/189) works for me and there was obviously a mistake.

I think there are more, because our cloop is identified as ntfs which it is not.

**Comment by HappyBasher** [comment]
AFAIK this affects a former PR from @PLanB2008.

**Comment by helge42** [comment]
My pull request wasn't the cause. The cause is that the determination of fstype in the function fstype() is to simple. With my cloop-file

dd if=/dev/cloop bs=128k count=2

contains the strings:
ntfs.mod
ntfscomp.mod
ntfs.mod
ntfscomp.mod
ntfs.mod
ntfscomp.mod

Therefor the function fstype() yields ntfs. Since it is actually an ext4 cloop the mount with mountpart() fails.

You can revert my pull request. I am working on another solution:
ntfslabel -n /dev/cloop && echo "ntfs"
this is another test to check if it is an ntfs filesystem in the cloop.

**Comment by HappyBasher** [comment]
You are right. There are better methods to get the filesystem type. I'll fix this.

**Comment by helge42** [comment]
I will post tomorrow my (partial ) fix.
The problem is that fdisk can not work on /dev/cloop and you can not use fdisk for this.

Is it possible to use fstype_startconf() for this and skip the function fstype()?  
if an administrator has placed a wrong cloop linbocmd will then fail. But an administrator should not do this 😉 .

**Comment by HappyBasher** [comment]
`blkid` does the trick.
