### ISSUE TITLE
udhcpc: dns labels can actually start with a number

### ISSUE THREAD

**Issue by GregorKopka** [linuxmuster/linuxmuster-linbo#48]
When trying babo-testing of linuxmuster-linbo the clients all get a hostname of 'bad'.
With prior version this client names like '18-105-23' (building-room-machine format, which are valid DNS labels) worked without problems.

This is because of known issue with udhcpc:
https://git.busybox.net/busybox/commit/?id=c29021e2a594fb29471c8c7e61ab8f45296622ba

Please integrate the fix in the link or disable ENABLE_FEATURE_UDHCPC_SANITIZEOPT when building busybox/udhcpc to preserve current functionality.

**Comment by GregorKopka** [comment]
Any news on this?

**Comment by HappyBasher** [comment]
Published in linuxmuster-linbo7 2.3.64.
