### ISSUE TITLE
shutdown option poweroff the computer before uploading an image

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-linbo#65]
If I check the shutdown option in Linbo it shutdowns the computer after creating the image but before uploading it. The same applies to if I check the shutdown option when I just want to upload an image.

Version: 2.3.15, LMN 6.2

**Comment by HappyBasher** [comment]
Thank you for your comment. But I fear, this will never be fixed, because the further development of the old linbo client gui is not possible with reasonable effort.
