### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by baumhof** [linuxmuster/linuxmuster-linbo#67]
In der Linbo GUI passiert es gerne mal, dass ein Klick als zwei interpretiert wird.
Das führt gerade bei der Imageerstellung immer mal wieder zu Problemen, weil ein Image erstellt wird und gleichzeitig der freie Platz auf der Pasrtition genullt wird: resultat: Imageerstellung bricht ab.

Vorschlag (Request): läuft ein Imageerstellungs-prozess, so kann kein zweiter gestartet werden.

**Comment by HappyBasher** [comment]
Das ist ein Fehler in der Linbo-Gui. Die wird leider nicht mehr weitergepflegt.
