### ISSUE TITLE
check if $HOME of linuxadmin / admin user is empty to prevent errors on login

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-linbo#69]
Because this is an error that happens from time to time (especially for new users), add a check before creating a image of Ubuntu/HULC/...

**Comment by HappyBasher** [comment]
Since linbo does not know about any admin user this is no task for it.

**Comment by zefanja** [comment]
I would be helpful, esp. for new users and would it make easier as supporter.

Linbo could get the template user from the linuxmuster-client config: https://github.com/linuxmuster/linuxmuster-client/blob/cf1334953f99f6d734b0b29652f4aeeaf0bea900/etc/config#L9
