### ISSUE TITLE
automatically apply ntfsfix to a partition, if dirty bit set

### ISSUE THREAD

**Issue by ghost** [linuxmuster/linuxmuster-linbo#70]
A set dirty bit might leave a computer in an unusuable state, making it necessary (though it may not be needed or wanted) to sync the hard disk.

If LINBO recognizes that a NTFS-partition is unmountable, it could (with or without a check for the error) use ntfsfix to clean the dirty bit and try again.

It might be of rare use, especially if "start" is not used in favour of sync/new+start. But it removes a situation where LINBO is some kind of a show-stopper (as without LINBO Windows would just start and fix the problem itself).

**Comment by PLanB2008** [comment]
+1

**Comment by PLanB2008** [comment]
Any progress on this issue?

**Comment by HappyBasher** [comment]
Fixed, see #124
