### ISSUE TITLE
linbo-remote -i ip-desrechners -p format:2,sync:2,start:2 funktioniert nicht richtig

### ISSUE THREAD

**Issue by aloisr** [linuxmuster/linuxmuster-linbo#77]
Hallo,

setzt man an der Konsole den Befehl

linbo-remote -i ip-desrechners -p format:2,sync:2,start:2

ab und startet die betroffenen Rechner, dann bleiben die Rechner mit der Meldung

> /dev/sda2 contains a ext4 file system
> Proceed anyway? (y,n)

stehen und erwarten die o.a. Eingabe.

linbo-remote -i ip-desrechners -p format:1,sync:1,start:1

funktioniert erwartungsgemäß.

Gruß

Alois

**Comment by HappyBasher** [comment]
The number after the format command defines the partition as entered in start. conf and is not necessarily the same as the number that defines the operating system. Example: The first operating system is installed on the third partition:
linbo-remote -c format:3,sync:1,start:1 -i <ip>
