### ISSUE TITLE
(extract and patch) or set UUID for the first harddisk

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster/linuxmuster-linbo#78]
Problem wurde von Holger untersucht:
https://ask.linuxmuster.net/t/linbo-2-3-26-0-macht-probleme/1226/29?u=machtdochnix

Mögliche Lösungsansätze:
https://ask.linuxmuster.net/t/linbo-2-3-26-0-macht-probleme/1226/30?u=machtdochnix
bzw noch besser.
https://ask.linuxmuster.net/t/linbo-2-3-26-0-macht-probleme/1226/33?u=machtdochnix

**Comment by HappyBasher** [comment]
Die einfachere Lösung scheinen mir Labels zu sein. Die werden von Linbo schon unterstützt nur beim Mounten noch nicht verwendet.

**Comment by HappyBasher** [comment]
Please check, if this issue can be resolved with use of partition labels.

**Comment by MachtDochNix** [comment]
Moin Thomas!

Just now in the Discourse came the feedback: Problem solved.

[https://ask.linuxmuster.net/t/linbo-2-3-26-0-macht-probleme/1226/83?u=machtdochnix]()

Issue solved.

Thank you!

Thorsten

**Comment by HappyBasher** [comment]
Solved.
