### ISSUE TITLE
Report from the community regarding the structure of the partitions

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster/linuxmuster-linbo#79]
Hallo!

Wenn es an dem ist, dann sollte die Cache nicht die letzte Partition auf der Platte sein.
See: https://ask.linuxmuster.net/t/win10-uefi-linbo-loesung/1639

Beste Grüße

Thorsten

**Comment by HappyBasher** [comment]
No issue for Linbo, I think. Should be documented.
