### ISSUE TITLE
Feature Request: Anzeige des aktuellen Status ...

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster/linuxmuster-linbo#80]
auch bei remote gesteuerten Clienst auf deren Monitoren.

Ist-Zustand: Bei remote gestarteten Sitzungen wird der Monitor des Clients ausgegraut. Im Status-Feld wird nicht angezeigt, was gerade auf dem Client passiert. Ein lokaler User vor der Maschine erhält keine Info was der Rechner gerade anstellt und könnte im schlimmsten Fall den Rechner einfach ausschalten. 

Gewünschter Soll-Zustand: Auch in dem Statusfeld wird das aktuelle Log ausgegeben. Zwar bestünde immer noch des Ausschalten durch einen User, aber vielleicht würde die Hemmschwelle dieses zu tun etwas nach oben gesetzt.

Hallo Thomas,

es wäre schön, wenn Du die Thread in ASK kommentieren würdest. Ich habe meine Erfahrungen in den oben beschrieben Ist-Zusatnd einfließen lassen. (DAU)

 https://ask.linuxmuster.net/t/statusanzeige-bei-remote-sync/1708/1

-------------------
Feature Request: Displays the current status of remote-controlled clients on their monitors.

Current state: The client monitor is greyed out when remote sessions are started. The status field does not show what is currently happening on the client. A local user in front of the machine does not receive any information about what the computer is doing and could in the worst case simply switch off the computer. 

Desired target status: The current log is also displayed in the status field. Of course, switching off by a user would still exist, but maybe the inhibition threshold to do this would be set slightly higher.

Translated with www.DeepL.com/Translator

**Comment by HappyBasher** [comment]
At the moment we don't have a developer who knows the Linbo-Gui programming. I also don't know if it is possible to execute an ssh command on the Linbo-Gui with reasonable effort.
