### ISSUE TITLE
linbo_cmd - Nicht initialisierte Variable RC

### ISSUE THREAD

**Issue by HappyBasher** [linuxmuster/linuxmuster-linbo#82]
Hallo Thomas,
durch die Korrektur bei interruptible bin ich auf einen weiteren Fehler 
gestoßen.
Bei "Aktualisiere GRUB-Konfiguration" muss in Zeile 3028 vor dem download-
Aufruf RC=0 gesetzt werden, da sonst folgendes passieren kann:
download $myname.cfg schlägt fehl RC=1
download $group.cfg ist erfolgreich, aber der Wert RC=1 bleibt bestehen
und die Aktualisierung bricht mit einer Fehlermeldung ab.

Gruß,
Frank

**Comment by HappyBasher** [comment]
In line 2955 RC is set to 0.

**Comment by fschuett** [comment]
Ich habe mich unklar ausgedrückt. Die Variable wird zwar zu Beginn initialisiert, sie muss aber nach jedem Schleifendurchlauf wieder auf RC=0 gesetzt werden, weil nur auf 1 gesetzt wird, nicht aber auf 0, wenn der download erfolgreich war.

diff --git a/linbofs/usr/bin/linbo_cmd b/linbofs/usr/bin/linbo_cmd
index ef5d32c6ee..4ce9f0c624 100755
--- a/linbofs/usr/bin/linbo_cmd
+++ b/linbofs/usr/bin/linbo_cmd
@@ -3026,6 +3026,7 @@ update(){
     else
       md5_before="$(md5sum "$(basename "$i")" 2> /dev/null | awk '{ print $1 }')"
     fi
+    RC=0
     download "$server" "$i" || RC=1
     if [ "$RC" = "1" ]; then
       # reset hostcfg if download failed

**Comment by HappyBasher** [comment]
Ok, thank you for your contribution. I'll fix this in the next release.

**Comment by HappyBasher** [comment]
Fixed in release 2.3.36
