### ISSUE TITLE
linbo_cmd: partnr - fix

### ISSUE THREAD

**Issue by fschuett** [linuxmuster/linuxmuster-linbo#87]
Hallo Thomas,
die Bestimmung der Partitionsnummer bei linbo_cmd schlägt bei Laufwerken fehl, die von der Art *p1 sind. Der angehängte Patch behebt dieses Problem, das sich an drei Stellen auswirkt.

Gruß,
Frank

[linbo_cmd.zip](https://github.com/linuxmuster/linuxmuster-linbo/files/1861769/linbo_cmd.zip)

**Comment by HappyBasher** [comment]
Should be fixed in the meantime.
