### ISSUE TITLE
linbo-ssh fails because wrong permissions of .ssh/authorized_keys

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-linbo#89]
Hi there,
in 
/usr/sbin/update-linbofs

the authorized_keys is created with bad permissions which results in impossible logins. Possible fix: changing file permissions :

 # provide dropbear ssh host key
 mkdir -p etc/dropbear
 cp $SYSDIR/linbo/dropbear_*_host_key etc/dropbear
 mkdir -p etc/ssh
 cp $SYSDIR/linbo/ssh_host_*_key* etc/ssh
 mkdir -p .ssh
 cat /root/.ssh/id_*.pub > .ssh/authorized_keys
 chmod 644 .ssh/authorized_keys
 chmod 755 .ssh

**Comment by HappyBasher** [comment]
Not reproduceable. Is this issue already present?

**Comment by HappyBasher** [comment]
Again, how may I reproduce this? I have never watched this invoking _update-linbofs_  and doing _linbo-ssh_ with lmn7 a million times. I prefer to know which event causes the unsecure permissions on authorized_keys because _update-linbofs_ creates them correctly.
I suppose this issue is due to an specific setup.

**Comment by HappyBasher** [comment]
Not reproduceable.

**Comment by PLanB2008** [comment]
It would make much more sense to wait for a proper answer then just closing all issues.

I'll provide the information how to reproduce this. It happened to me in every lmn7 installation.

No one opens issues just for fun...

**Comment by HappyBasher** [comment]
Okay, you are free to reopen. No harm meant.

**Comment by netzint** [comment]
I had the exact same problem and the solution of PlanB2008 is working for me too.

**Comment by netzint** [comment]
Please reopen this Ticket. Many regards, Maurice

**Comment by HappyBasher** [comment]
I will reopen it, but netzint is the only one who reports this issue. I think there is something special with your setup, that causes files to be created with non standard and unsecure permissions. I fear there are other files which were created with unsecure permissions. Therefore I strongly recommend to find out why your system does not behave like the standard. What filesystem do you use for /var?

**Comment by HappyBasher** [comment]
I notice something else: You write dropbear does not start because of too open permissions of the file authorized_keys. However, this file does not matter when starting the service. Rather it depends on the rights of the hostkeys under /etc/dropbear.
On my freshly prepared system this looks like this directly after setup:
```
root@server:~# ls -la /var/cache/linuxmuster/linbo/linbofs*/.ssh/
/var/cache/linuxmuster/linbo/linbofs64/.ssh/:
insgesamt 12
drwxr-xr-x  2 root root 4096 Feb 26 14:57 .
drwxr-xr-x 16 root root 4096 Feb 26 14:57 ..
-rw-r--r--  1 root root 1324 Feb 26 14:57 authorized_keys

/var/cache/linuxmuster/linbo/linbofs-np/.ssh/:
insgesamt 12
drwxr-xr-x  2 root root 4096 Feb 26 14:56 .
drwxr-xr-x 14 root root 4096 Feb 26 14:56 ..
-rw-r--r--  1 root root 1324 Feb 26 14:56 authorized_keys

/var/cache/linuxmuster/linbo/linbofs/.ssh/:
insgesamt 12
drwxr-xr-x  2 root root 4096 Feb 26 14:56 .
drwxr-xr-x 14 root root 4096 Feb 26 14:56 ..
-rw-r--r--  1 root root 1324 Feb 26 14:56 authorized_keys
```
```
root@server:~# ls -la /var/cache/linuxmuster/linbo/linbofs*/etc/dropbear/
/var/cache/linuxmuster/linbo/linbofs64/etc/dropbear/:
insgesamt 16
drwxr-xr-x 2 root root 4096 Feb 26 14:57 .
drwxr-xr-x 6 root root 4096 Feb 26 14:57 ..
-rw------- 1 root root  457 Feb 26 14:57 dropbear_dss_host_key
-rw------- 1 root root  805 Feb 26 14:57 dropbear_rsa_host_key

/var/cache/linuxmuster/linbo/linbofs/etc/dropbear/:
insgesamt 16
drwxr-xr-x 2 root root 4096 Feb 26 14:56 .
drwxr-xr-x 6 root root 4096 Feb 26 14:56 ..
-rw------- 1 root root  457 Feb 26 14:56 dropbear_dss_host_key
-rw------- 1 root root  805 Feb 26 14:56 dropbear_rsa_host_key

/var/cache/linuxmuster/linbo/linbofs-np/etc/dropbear/:
insgesamt 16
drwxr-xr-x 2 root root 4096 Feb 26 14:56 .
drwxr-xr-x 6 root root 4096 Feb 26 14:56 ..
-rw------- 1 root root  457 Feb 26 14:56 dropbear_dss_host_key
-rw------- 1 root root  805 Feb 26 14:56 dropbear_rsa_host_key
```

This state is precisely archived to linbofs*.lz and linbo-ssh behaves as expected.

Please check the permissions of the according files on your system after setup before you invoke linbo-ssh.

**Comment by HappyBasher** [comment]
Have you checked this? I'm sure the permissions are not the reason of your problem.
