### ISSUE TITLE
Remove Rows in win10.global.reg template

### ISSUE THREAD

**Issue by netzint** [linuxmuster/linuxmuster-linbo#90]
This rows should be removed for LMN7

; notwendig, damit der Domaenenbeitritt klappt
[HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\services\LanmanWorkstation\Parameters]
"DomainCompatibilityMode"=dword:00000001
"DNSNameResolutionRequired"=dword:00000000

**Comment by HappyBasher** [comment]
Fixed in commit cec81b9.
