### ISSUE TITLE
win10 global reg hostname length

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-linbo#93]
We should verify the length of the hostname on some point.

Windows only accepts netbios names with the length of 15 bytes which results in 15 characters for a netbios hostname. 
Windows goes on and shortens the netbios name. We should either do the same during the patch process, which would be pretty elegant, or deny hostnames this length at all during the linuxmuster-add-devices process.

**Comment by HappyBasher** [comment]
This should be checked by sophomorix-devices.
