### ISSUE TITLE
Device Registration in LMN7

### ISSUE THREAD

**Issue by PLanB2008** [linuxmuster/linuxmuster-linbo#94]
Linbo still uses the old csv style when adding a workstation in the devices.csv file. This should be changed to our new format like:

r100;r100-pc01;ubuntu;de:b7:ca:4e:a3:0d;10.0.10.10;;;;classroom-studentcomputer;1;1;;;;;

I also think we should either set the role to classroom-studentcomputer, or offer a dropdown for the user to pick a role.

**Comment by HappyBasher** [comment]
Will be fixed in 2.3.42. _rsync-post-upload.sh_ will repair the line accordlngly.
