### ISSUE TITLE
Create multicast error when one image name is included as part of another.

### ISSUE THREAD

**Issue by MachtDochNix** [linuxmuster/linuxmuster-linbo#95]
This was reported in the forum with a description of the error source in /etc/init.d/linbo-multicast.

https://ask.linuxmuster.net/t/fehler-beim-multicast-erzeugen-wenn-ein-image-name-im-anderen-enthalten/2722

###

Fehler beim Multicast erzeugen, wenn ein Image-Name als Teil in einem anderen enthalten ist.

Dieses wurde im Forum gemeldet mit Beschreibung der Fehlerquelle in /etc/init.d/linbo-multicast

https://ask.linuxmuster.net/t/fehler-beim-multicast-erzeugen-wenn-ein-image-name-im-anderen-enthalten/2722

**Comment by HappyBasher** [comment]
Will be fixed in 2.3.42.

**Comment by baumhof** [comment]
Hi,
users report that it might not be fixed yet:
https://ask.linuxmuster.net/t/fehler-beim-multicast-erzeugen-wenn-ein-image-name-im-anderen-enthalten/2722/3
LG

Holger
