### ISSUE TITLE
Feature Request: add an option to linbo-remote to select menu-entry in Grub

### ISSUE THREAD

**Issue by zefanja** [linuxmuster/linuxmuster-linbo#97]
On most of our computers, we have just one OS installed, so we use GRUB to boot it directly, without booting Linbo first (because its faster).

The problem is, that we can't use linbo-remote anymore to sync the computers automatically in the morning, because we can't tell grub to boot Linbo instead of the OS. 

As workaround we used something like this in the past:
```
insmod datehook
if [ $MINUTE -lt 10 ]; then PADDING="0"; else PADDING=""; fi
TIME=$HOUR$PADDING$MINUTE
if [ $TIME -ge 030 -a $TIME -lt 1000 ]; then
    set default=1
fi
```
to boot Linbo during night time and the OS during day time. 

**Feature Request**
It would be great to use `linbo-remote` to specify a menu entry in Grub that you want to boot next time, or something like a `--linbo` option to boot Linbo. 

**Ideas**
* One way to do this, would be to have a custom `grub.cfg` that would be served one next boot instead of `gruppe.cfg`.
* another way is to update the `dhcpd.conf` and set another `extension-path` (is this used to determine which grub.cfg will be used?)
* update `grub.cfg` to look for a specifiy dhcp option and choose menu entry based on it (similar to idea above, needs restart and update of `dhcpd.conf`)

What do you think?

**Comment by zefanja** [comment]
@HappyBasher Any thoughts? Is this do-able?

**Comment by HappyBasher** [comment]
In fact I'm thinking about an extra script e.g. linbo-grub to manipulate the boot behaviour. Let's see.

**Comment by HappyBasher** [comment]
This will be a task in linuxmuster-linbo7.
