### ISSUE TITLE
Neuer Treiber in Linbo nötig!?

### ISSUE THREAD

**Issue by aloisr** [linuxmuster/linuxmuster-linbo#99]
Hallo Thomas,

im Forum unter https://ask.linuxmuster.net/t/registrierung-nicht-moeglich-linbo-offline/2852 wurde erwähnt, dass eventuell ein neuer Treiber in Linbo eingepflegt werden müsse.

Schaust Du Dir das mal an.

Gruß

Alois

**Comment by MachtDochNix** [comment]
Hallo Thomas!

Nachmal Probleme mit e1000e Treiber. Bitte um Stellungnahme in:

https://ask.linuxmuster.net/t/neue-pcs-linbo-haengt/2971/19

Liebe Grüße

Thorsten

**Comment by HappyBasher** [comment]
Hopefully fixed in 2.3.39 with new kernel version.
